#syntax=docker/dockerfile:1
FROM golang:1.21.6-alpine as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git
WORKDIR /l2geth
COPY ./l2geth ./
RUN make geth

# Pull Geth into a second stage deploy alpine container
FROM alpine:3.19
RUN apk add --no-cache ca-certificates jq curl
COPY --from=builder /l2geth/build/bin/geth /usr/local/bin/
EXPOSE 8545 8546 30303
COPY ./ops/scripts/geth.sh .
ENTRYPOINT ["geth"]
